"""Staged copy of the authoritative persona registry — Issue #5420 (PMM-03).

THIS FILE IS GENERATED by ``scripts/sync_personas.py``.
DO NOT edit manually.

Source: ``modules/agent-factory/webhook-ingress/lambda/common/personas.py``

The parity test asserts this copy matches the source, so drift is a red
test rather than a silent divergence.
"""

from __future__ import annotations

LABEL_TO_PERSONA: dict[str, str] = {
    "agent-architect": "architect",
    "agent-operations": "operations",
    "agent-reviewer": "reviewer",
    "developer": "developer",
    "malware-analysis-agent": "malware-analysis-agent",
    "pm": "pm",
    "superpower": "pt-superpower",
}

MENTION_TO_PERSONA: dict[str, str] = {
    "@agent-aidlc": "aidlc",
    "@agent-architect": "architect",
    "@agent-codex": "codex",
    "@agent-codex-reviewer": "agent-codex-reviewer",
    "@agent-developer": "developer",
    "@agent-malware-analysis-agent": "malware-analysis-agent",
    "@agent-operations": "operations",
    "@agent-pm": "pm",
    "@agent-product": "product",
    "@agent-reviewer": "reviewer",
    "@agent-superplane-operator": "superplane-operator",
    "@agent-superplane-researcher": "superplane-researcher",
    "@agent-superpower": "pt-superpower",
}

AUTOMATIC_PERSONAS: set[str] = {
    "agent-codex-reviewer",
}

PERSONA_COMPATIBILITY_CLASS: dict[str, str] = {
    "agent-codex-reviewer": "codex-sdk",
    "aidlc": "claude-agent-sdk",
    "architect": "claude-agent-sdk",
    "codex": "claude-agent-sdk",
    "developer": "claude-agent-sdk",
    "malware-analysis-agent": "claude-agent-sdk",
    "operations": "claude-agent-sdk",
    "pm": "claude-agent-sdk",
    "product": "claude-agent-sdk",
    "pt-superpower": "claude-agent-sdk",
    "reviewer": "claude-agent-sdk",
    "superplane-operator": "claude-agent-sdk",
    "superplane-researcher": "claude-agent-sdk",
}

COMPATIBILITY_CLASS_HARNESS_CONTRACT_REVISION: dict[str, str] = {
    "claude-agent-sdk": "0.3.220",
    "codex-sdk": "0.155.1",
}

# The canonical set of all valid personas — union of all mapping targets and automatic personas.
VALID_PERSONAS: set[str] = set(MENTION_TO_PERSONA.values()) | set(LABEL_TO_PERSONA.values()) | AUTOMATIC_PERSONAS
