"""Staged copy of the authoritative persona registry — Issue #5420 (PMM-03).

THIS FILE IS GENERATED by ``scripts/sync_personas.py``.
DO NOT edit manually.

Source: ``modules/agent-factory/webhook-ingress/lambda/common/personas.py``

The parity test asserts this copy matches the source, so drift is a red
test rather than a silent divergence.
"""

from __future__ import annotations

LABEL_TO_PERSONA: dict[str, str] = {
    "agent-architect": "architect",
    "agent-operations": "operations",
    "agent-reviewer": "reviewer",
    "developer": "developer",
    "malware-analysis-agent": "malware-analysis-agent",
    "pm": "pm",
    "superpower": "pt-superpower",
}

MENTION_TO_PERSONA: dict[str, str] = {
    "@agent-aidlc": "aidlc",
    "@agent-architect": "architect",
    "@agent-codex": "codex",
    "@agent-developer": "developer",
    "@agent-malware-analysis-agent": "malware-analysis-agent",
    "@agent-operations": "operations",
    "@agent-pm": "pm",
    "@agent-product": "product",
    "@agent-reviewer": "reviewer",
    "@agent-superplane-operator": "superplane-operator",
    "@agent-superplane-researcher": "superplane-researcher",
    "@agent-superpower": "pt-superpower",
}

# The canonical set of all valid personas — union of all mapping targets.
VALID_PERSONAS: set[str] = set(MENTION_TO_PERSONA.values()) | set(LABEL_TO_PERSONA.values())
