"""Persona-model catalogue service — Issue #5420 (PMM-03).

The routes are HTTP; this module is the decisions.

Design: ``docs/design-notes/5420-persona-and-model-catalogue.md``.

Owns:
  - Persona catalogue assembly (§2, AC-01/AC-02)
  - Selectable-model catalogue with the intersection filter (§3, §6.2)
  - Alias-to-canonical resolution (§3.6, AC-03)
  - Invocability evidence lookup (§4)
  - SDK-generated request-shape lookup used by evidence reads (§4, AC-04)
  - The shared validation function (§6.3) consumed by PMM-02 and PMM-06
  - Allowlist report (§5, C2)
"""

from __future__ import annotations

import fnmatch
from typing import Literal

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from src.admin.persona_models._personas import VALID_PERSONAS
from src.admin.persona_models.catalogue import (
    COMPATIBILITY_CLASS_CLAUDE,
    PERSONA_ALLOWED_PATTERNS,
    PLATFORM_MODEL_CATALOGUE,
    CatalogueModel,
    aliases_for_model,
    catalogue_lookup,
    persona_compatibility_class,
    persona_is_configurable,
    persona_not_configurable_reason,
    resolve_alias,
)
from src.admin.persona_models.catalogue_schemas import (
    InvocabilityEvidence,
    ModelCatalogueRow,
    PersonaCatalogueRow,
    SelectionRejection,
    SelectionResult,
)
from src.shared.models.persona_model_catalogue import ModelInvocabilityEvidence

# ---------------------------------------------------------------------------
# Display metadata for personas
# ---------------------------------------------------------------------------
# Brief descriptions for the catalogue.  These are presentational and
# derived from docs/agent-catalogue.md.

_PERSONA_DISPLAY: dict[str, tuple[str, str]] = {
    "developer": ("Developer", "Code implementation, unit tests, and PRs"),
    "pm": ("PM", "Project management, planning and coordination"),
    "operations": ("Operations", "Infrastructure and deployment operations"),
    "reviewer": ("Reviewer", "Code review and quality assurance"),
    "architect": ("Architect", "System design and architecture decisions"),
    "product": ("Product", "Product management and requirements"),
    "malware-analysis-agent": ("Malware Analysis", "Security and malware analysis"),
    "pt-superpower": ("Superpower", "General-purpose superpower agent"),
    "superplane-operator": ("Superplane Operator", "Superplane domain operations"),
    "superplane-researcher": ("Superplane Researcher", "Superplane domain research"),
    "aidlc": ("AIDLC", "AI development lifecycle inception"),
    "codex": ("Codex", "Code generation supervisor using Codex as a delegated tool"),
}


# ---------------------------------------------------------------------------
# Rejection helper — mirrors bedrock_routing.service.MappingRejectedError
# ---------------------------------------------------------------------------


class CatalogueError(Exception):
    """A catalogue refusal with a machine-readable reason code.

    Same shape as ``bedrock_routing.service.MappingRejectedError`` so the
    routes module converts it to the shared ``422 {reason, message}`` shape.
    """

    def __init__(self, reason: str, message: str) -> None:
        self.reason = reason
        self.message = message
        super().__init__(message)


def compute_request_shape_sha256(model_id: str) -> str:
    """Return the checked-in SDK-generated request-shape digest for a model.

    The model is already a separate evidence-key dimension.  The body digest is
    generated by the pinned Node SDK against a local capture proxy; the Gateway
    must never reconstruct or guess that body in Python.
    """
    from src.admin.persona_models.request_shape_manifest import expected_request_shape

    digest = expected_request_shape(model_id)
    if digest is None:
        raise RuntimeError(f"No SDK-generated request shape for catalogue model {model_id}")
    return digest


# ---------------------------------------------------------------------------
# Persona catalogue (§2, AC-01/AC-02)
# ---------------------------------------------------------------------------


def build_persona_catalogue() -> list[PersonaCatalogueRow]:
    """Build the persona catalogue from the authoritative registry.

    Derived from ``VALID_PERSONAS`` at call time — any second list fails
    AC-01 by construction.
    """
    rows: list[PersonaCatalogueRow] = []
    for persona_key in sorted(VALID_PERSONAS):
        display_name, purpose = _PERSONA_DISPLAY.get(persona_key, (persona_key.replace("-", " ").title(), ""))
        compat_class = persona_compatibility_class(persona_key)
        rows.append(
            PersonaCatalogueRow(
                key=persona_key,
                display_name=display_name,
                purpose=purpose,
                configurable=persona_is_configurable(persona_key),
                not_configurable_reason=persona_not_configurable_reason(persona_key),
                compatibility_class=compat_class or COMPATIBILITY_CLASS_CLAUDE,
            )
        )
    return rows


# ---------------------------------------------------------------------------
# Evidence lookup (§4) — full 6-column primary key
# ---------------------------------------------------------------------------


async def lookup_evidence(
    db: AsyncSession,
    *,
    account_id: str,
    region: str,
    canonical_model_id: str,
    compatibility_class: str,
    harness_contract_revision: str,
    request_shape_sha256: str,
) -> ModelInvocabilityEvidence | None:
    """Look up evidence with the complete 6-column primary key.

    Every dimension matters: a different destination, model, class, harness
    revision, or request shape is a different evidence key.  Dropping any
    dimension allows an arbitrary row to match (operator review item 3).
    """
    row = await db.scalar(
        select(ModelInvocabilityEvidence).where(
            ModelInvocabilityEvidence.account_id == account_id,
            ModelInvocabilityEvidence.region == region,
            ModelInvocabilityEvidence.canonical_model_id == canonical_model_id,
            ModelInvocabilityEvidence.compatibility_class == compatibility_class,
            ModelInvocabilityEvidence.harness_contract_revision == harness_contract_revision,
            ModelInvocabilityEvidence.request_shape_sha256 == request_shape_sha256,
        )
    )
    return row


def _evidence_to_schema(
    evidence: ModelInvocabilityEvidence | None,
) -> InvocabilityEvidence | None:
    """Convert a DB evidence row to the API schema.

    Preserves all evidence fields, including for stale evidence — the operator
    review requires stale evidence to be actionable (item 5), not discarded.
    """
    if evidence is None:
        return None
    return InvocabilityEvidence(
        account_id=evidence.account_id,
        region=evidence.region,
        verified_at=evidence.verified_at_utc,
        expires_at=evidence.expires_at_utc,
        stale=evidence.is_stale,
        request_shape_sha256=evidence.request_shape_sha256,
    )


def _invocable_state(evidence: ModelInvocabilityEvidence | None) -> bool | None:
    """Tri-state invocability: True (proven), False (refused), None (unproven).

    §4.7: null means unproven (probing disabled or no evidence); false means
    a probe ran and the model refused.  Conflating them tells an operator a
    model is broken when nothing has been tried.
    """
    if evidence is None:
        return None
    if evidence.is_stale:
        return None
    return evidence.is_proven


# ---------------------------------------------------------------------------
# Probe posture reported by catalogue reads; execution lives on the internal worker API
# ---------------------------------------------------------------------------


def is_probe_enabled() -> bool:
    """Whether the probe mechanism is enabled and has budget to spend."""
    from src.shared.config import get_settings

    settings = get_settings()
    return (
        settings.model_probe_enabled
        and settings.model_probe_max_slots_per_cycle > 0
        and settings.model_probe_budget_usd_per_cycle > 0
        and settings.model_probe_max_budget_usd_per_attempt > 0
    )


# ---------------------------------------------------------------------------
# Tenant allowlist evaluation (§3.5, C2)
# ---------------------------------------------------------------------------


def _model_matches_patterns(canonical_model_id: str, patterns: list[str] | None) -> bool:
    """Check if a model ID matches any fnmatch pattern in the list.

    Only ``None`` inherits the persona-selection baseline (D3: no explicit
    allowlist inherits a versioned platform baseline).  An explicit empty list
    is a configured deny-all policy and must never widen back to the baseline.
    """
    effective = patterns if patterns is not None else list(PERSONA_ALLOWED_PATTERNS)
    return any(fnmatch.fnmatch(canonical_model_id, p) for p in effective)


def _model_matches_service_restrictions(
    canonical_model_id: str,
    restriction_pattern_sets: list[list[str]] | None,
) -> bool:
    """Apply every explicit registered service-principal restriction.

    One canonical service principal may have several active Agent Registry
    aliases.  Its preference is shared by those aliases, so a model is safe to
    save only when it satisfies every non-empty registry restriction.  Empty
    ``allowed_models`` means that alias inherits the platform baseline; it is
    not an explicit deny-all rule.
    """
    if not restriction_pattern_sets:
        return True
    return all(not patterns or any(fnmatch.fnmatch(canonical_model_id, pattern) for pattern in patterns) for patterns in restriction_pattern_sets)


# ---------------------------------------------------------------------------
# Service-principal restrictions — gate 4 (§3.1, operator round-4 item 4)
# ---------------------------------------------------------------------------
# The Agent Registry ``allowed_models`` set is the existing registered
# service-principal restriction.  PMM-03 makes it load-bearing instead of
# leaving it stranded in DynamoDB.  Routes pass it as one or more server-
# resolved pattern sets; callers never submit these patterns.  This gate also:
#   * Enforces principal *status* where it is known.  A suspended or retired
#     principal may select nothing; this is PMM-02's ``ServicePrincipal.status``
#     vocabulary (active / suspended / retired), wired for real once PMM-02
#     merges and its store is importable.
#   * Requires a canonical principal identity for a service_account.  R1 makes
#     the canonical service-principal ID the owner of a preference, so a
#     service_account whose canonical ID could not be resolved cannot have a
#     preference validated *for* it.  Fail closed rather than fall back to a
#     mutable name.
#
# An organization with no explicit policy inherits the versioned platform
# baseline through ``_model_matches_patterns``.  This is the locked D3 ruling,
# not unrestricted access.

PrincipalStatus = Literal["active", "suspended", "retired"]

_SELECTION_BLOCKING_STATUSES: frozenset[str] = frozenset({"suspended", "retired"})


def evaluate_principal_restrictions(
    *,
    principal_kind: Literal["human", "service_account"],
    canonical_principal_id: str | None,
    principal_status: str | None = None,
) -> tuple[bool, str | None]:
    """Gate 4: may this principal select a model at all?

    Returns ``(permitted, reason)``.  ``reason`` is ``None`` when permitted.

    This helper is the principal-level lifecycle/identity portion of gate 4.
    The model-specific Agent Registry restriction is applied separately by
    ``_model_matches_service_restrictions`` after the organization policy.

    Args:
        principal_kind: Canonical vocabulary — "human" or "service_account".
        canonical_principal_id: The opaque immutable ADP principal ID (R1).
        principal_status: PMM-02 ``ServicePrincipal.status`` when known.
            ``None`` means "no principal record applies" (the human case), not
            "assume active" for a service_account.
    """
    if principal_status is not None and principal_status in _SELECTION_BLOCKING_STATUSES:
        return False, "not_permitted"

    if principal_kind == "service_account" and not canonical_principal_id:
        # R1: the canonical ID owns the preference.  Without it there is no
        # subject to validate for, and substituting a mutable name is exactly
        # the aliasing hazard R1 exists to remove.
        return False, "not_permitted"

    return True, None


# ---------------------------------------------------------------------------
# Selectable-model catalogue (§3.1, §6.2)
# ---------------------------------------------------------------------------


async def build_model_catalogue(
    db: AsyncSession,
    *,
    persona_key: str,
    account_id: str | None = None,
    region: str | None = None,
    tenant_allowed_patterns: list[str] | None = None,
    service_restriction_pattern_sets: list[list[str]] | None = None,
    policy_unavailable_reason: str | None = None,
    principal_kind: Literal["human", "service_account"] = "human",
    canonical_principal_id: str | None = None,
    principal_status: str | None = None,
    require_evidence: bool = True,
) -> list[ModelCatalogueRow]:
    """Build the selectable-model catalogue for a persona and destination.

    Evaluates gates 1-5 in cheapest-first order (§3.1):
      1. Harness compatibility for the target persona's class
      2. Platform catalogue membership
      3. Tenant/organization allowlist
      4. Service-principal restrictions
      5. Invocability evidence

    The catalogue and ``validate_selection`` must agree, so both take the same
    policy inputs.  If they disagree, the screen offers a model that save
    rejects, or save accepts one dispatch cannot run (§6.3).
    """
    compat_class = persona_compatibility_class(persona_key)
    if compat_class is None:
        return []
    compatible_models = tuple(model for model in PLATFORM_MODEL_CATALOGUE if model.compatibility_class == compat_class)

    # Gate 4 is principal-level, so it is evaluated once rather than per model.
    principal_permitted, principal_reason = evaluate_principal_restrictions(
        principal_kind=principal_kind,
        canonical_principal_id=canonical_principal_id,
        principal_status=principal_status,
    )
    if not principal_permitted:
        # Still enumerate every model, each marked unselectable with its
        # reason: AC-01 requires the catalogue to stay honest about what
        # exists, and an empty list is indistinguishable from "no models".
        return [_model_row(model, selectable=False, reason=principal_reason, permitted=False) for model in compatible_models]

    if policy_unavailable_reason:
        return [
            _model_row(
                model,
                selectable=False,
                reason=policy_unavailable_reason,
                permitted=False,
            )
            for model in compatible_models
        ]

    rows: list[ModelCatalogueRow] = []
    for model in compatible_models:
        # Gates 1-2: only this harness class's platform catalogue entries are
        # enumerated. Other-class models are absent, never disabled choices.
        # (we are iterating the catalogue itself).

        # Gate 3: Tenant allowlist
        permitted = _model_matches_patterns(model.canonical_model_id, tenant_allowed_patterns)
        if not permitted:
            rows.append(_model_row(model, selectable=False, reason="not_permitted", permitted=False))
            continue

        # Gate 4: every real Agent Registry restriction for this canonical
        # service principal.  This is separate from the organization policy;
        # neither may widen the other.
        if not _model_matches_service_restrictions(model.canonical_model_id, service_restriction_pattern_sets):
            rows.append(_model_row(model, selectable=False, reason="not_permitted", permitted=False))
            continue

        # A saved preference is a choice, not a provider-access certificate.
        # The optional protected runtime retains its fresh-evidence gate.
        if not require_evidence:
            retired = model.lifecycle == "retired"
            rows.append(_model_row(model, selectable=not retired, reason="retired" if retired else None, permitted=True))
            continue

        # Gate 5: Invocability evidence
        evidence: ModelInvocabilityEvidence | None = None
        if account_id and region:
            shape_sha = compute_request_shape_sha256(model.canonical_model_id)
            evidence = await lookup_evidence(
                db,
                account_id=account_id,
                region=region,
                canonical_model_id=model.canonical_model_id,
                compatibility_class=model.compatibility_class,
                harness_contract_revision=model.harness_contract_revision,
                request_shape_sha256=shape_sha,
            )

        invocable = _invocable_state(evidence)

        # Retirement check (§4.5)
        if model.lifecycle == "retired":
            rows.append(
                _model_row(
                    model,
                    selectable=False,
                    reason="retired",
                    permitted=True,
                    invocable=invocable,
                    evidence=evidence,
                )
            )
            continue

        # Determine selectability based on invocability
        if invocable is True:
            rows.append(
                _model_row(
                    model,
                    selectable=True,
                    permitted=True,
                    invocable=True,
                    evidence=evidence,
                )
            )
        elif invocable is False:
            rows.append(
                _model_row(
                    model,
                    selectable=False,
                    reason="not_invocable",
                    permitted=True,
                    invocable=False,
                    evidence=evidence,
                )
            )
        else:
            # invocable is None — unproven.  Distinguish stale from no-attempt.
            if evidence is not None and evidence.is_stale:
                # Stale evidence: preserve the evidence row so the refusal is
                # actionable (operator review item 5).
                rows.append(
                    _model_row(
                        model,
                        selectable=False,
                        reason="evidence_stale",
                        permitted=True,
                        invocable=None,
                        evidence=evidence,
                    )
                )
            else:
                # No evidence at all — probing disabled or never attempted.
                rows.append(
                    _model_row(
                        model,
                        selectable=False,
                        reason="probing_disabled",
                        permitted=True,
                        invocable=None,
                        evidence=None,
                    )
                )

    return rows


def _model_row(
    model: CatalogueModel,
    *,
    selectable: bool,
    reason: str | None = None,
    permitted: bool | None = None,
    invocable: bool | None = None,
    evidence: ModelInvocabilityEvidence | None = None,
) -> ModelCatalogueRow:
    """Compose a model catalogue row from a catalogue entry and gate results."""
    return ModelCatalogueRow(
        canonical_model_id=model.canonical_model_id,
        aliases=list(aliases_for_model(model.canonical_model_id)),
        model_family=model.model_family,
        canonical_version=model.canonical_version,
        selectable=selectable,
        reason=reason,
        permitted=permitted,
        invocable=invocable,
        evidence=_evidence_to_schema(evidence),
        compatibility_class=model.compatibility_class,
        harness_contract_revision=model.harness_contract_revision,
        retired=model.lifecycle == "retired",
        price_context=None,  # §3.7: price context loaded separately
    )


# ---------------------------------------------------------------------------
# Shared validation function (§6.3) — FAIL-CLOSED
# ---------------------------------------------------------------------------


async def validate_selection(
    db: AsyncSession,
    *,
    org_id: str,
    principal_kind: Literal["human", "service_account"],
    canonical_principal_id: str,
    persona_key: str,
    model: str,
    account_id: str | None = None,
    region: str | None = None,
    tenant_allowed_patterns: list[str] | None = None,
    service_restriction_pattern_sets: list[list[str]] | None = None,
    policy_unavailable_reason: str | None = None,
    principal_status: str | None = None,
    require_evidence: bool = True,
) -> SelectionResult | SelectionRejection:
    """Validate whether a model is selectable for a principal and persona.

    **FAIL-CLOSED.** The only acceptable success is one backed by a fresh,
    exact-key evidence row for the server-resolved destination (operator
    review item 1).  Without evidence, the function refuses — it never
    certifies a selection on the strength of a price row or a listing.

    This is the single definition of "selectable" — called by the catalogue
    endpoint and by PMM-02's save path.  If they disagree, the screen offers
    a model that save rejects, or save accepts one that dispatch cannot run.

    Returns a ``SelectionResult`` on success or ``SelectionRejection`` on
    refusal.  The caller decides the HTTP shape: a catalogue renders the
    rejection as a row-level reason; a save converts it to a 422.

    Args:
        db: Database session.
        org_id: Tenant organization ID.
        principal_kind: "human" or "service_account".
        canonical_principal_id: The opaque immutable ADP principal ID (R1).
        persona_key: The persona to validate for.
        model: The model alias or canonical ID to validate.
        account_id: Effective destination account (resolved server-side).
        region: Effective destination region (resolved server-side).
        tenant_allowed_patterns: Organization's model allowlist patterns.
        principal_status: PMM-02 ``ServicePrincipal.status`` when a principal
            record applies.  ``None`` means no record applies (the human
            case) — it is not a shortcut for "active".
    """
    # Gate 0: Resolve alias → canonical
    resolved = resolve_alias(model)
    if resolved is None:
        # Not a known alias and not a catalogue entry
        catalogue_entry = catalogue_lookup(model)
        if catalogue_entry is None:
            return SelectionRejection(
                reason="unknown_model",
                message=f"'{model}' is not a recognized model alias or canonical identifier.",
            )
        resolved = catalogue_entry.canonical_model_id
    else:
        catalogue_entry = catalogue_lookup(resolved)

    if catalogue_entry is None:
        return SelectionRejection(
            reason="unknown_model",
            message=f"'{model}' resolves to '{resolved}' which is not in the platform catalogue.",
        )

    # Gate 1: Persona exists and is configurable
    compat_class = persona_compatibility_class(persona_key)
    if compat_class is None:
        return SelectionRejection(
            reason="unknown_persona",
            message=f"'{persona_key}' is not a registered persona.",
        )

    if not persona_is_configurable(persona_key):
        return SelectionRejection(
            reason="unknown_persona",
            message=f"'{persona_key}' is not configurable.",
        )

    # Gate 2: Harness compatibility
    if catalogue_entry.compatibility_class != compat_class:
        return SelectionRejection(
            reason="harness_incompatible",
            message=(f"'{resolved}' is a {catalogue_entry.compatibility_class} model but persona '{persona_key}' executes under {compat_class}."),
        )

    # Gate 3: Retirement
    if catalogue_entry.lifecycle == "retired":
        return SelectionRejection(
            reason="retired",
            message=f"'{resolved}' has been retired from the platform catalogue.",
        )

    # Gate 4a: Tenant allowlist — use provided patterns or persona baseline.
    if not _model_matches_patterns(resolved, tenant_allowed_patterns):
        return SelectionRejection(
            reason="not_permitted",
            message=f"'{resolved}' is not permitted by the organization's model policy.",
        )

    # Gate 4b: Service-principal restrictions (operator round-4 item 4).
    # The same gate the catalogue applies, so the two cannot disagree about
    # who may select — previously these arguments were accepted and ignored.
    principal_permitted, _principal_reason = evaluate_principal_restrictions(
        principal_kind=principal_kind,
        canonical_principal_id=canonical_principal_id,
        principal_status=principal_status,
    )
    if not principal_permitted:
        return SelectionRejection(
            reason="not_permitted",
            message=(
                f"Principal '{canonical_principal_id or '<unresolved>'}' "
                f"(kind={principal_kind}, status={principal_status or 'unknown'}) "
                "may not configure a persona model."
            ),
        )

    if policy_unavailable_reason:
        return SelectionRejection(
            reason=policy_unavailable_reason,
            message="The registered service-principal model policy could not be resolved safely.",
        )

    if not _model_matches_service_restrictions(resolved, service_restriction_pattern_sets):
        return SelectionRejection(
            reason="not_permitted",
            message=f"'{resolved}' is not permitted by the registered service-principal model policy.",
        )

    if not require_evidence:
        return SelectionResult(
            canonical_model_id=resolved,
            compatibility_class=compat_class,
            harness_contract_revision=catalogue_entry.harness_contract_revision,
        )

    # Gate 5: Invocability evidence — FAIL-CLOSED
    # Without destination context, we cannot look up evidence.
    if not account_id or not region:
        return SelectionRejection(
            reason="probing_disabled",
            message=("No effective destination resolved for this caller. Model selection requires destination-specific invocability evidence."),
        )

    shape_sha = compute_request_shape_sha256(resolved)
    evidence = await lookup_evidence(
        db,
        account_id=account_id,
        region=region,
        canonical_model_id=resolved,
        compatibility_class=catalogue_entry.compatibility_class,
        harness_contract_revision=catalogue_entry.harness_contract_revision,
        request_shape_sha256=shape_sha,
    )

    if evidence is None:
        return SelectionRejection(
            reason="probing_disabled",
            message=(
                f"No invocability evidence exists for '{resolved}' at "
                f"destination {account_id}/{region}. "
                "Probing is disabled or has not yet run for this model."
            ),
        )

    if evidence.is_stale:
        return SelectionRejection(
            reason="evidence_stale",
            message=(
                f"Invocability evidence for '{resolved}' at "
                f"destination {account_id}/{region} expired at "
                f"{evidence.expires_at_utc.isoformat()}. A fresh probe is required."
            ),
        )

    if not evidence.is_proven:
        return SelectionRejection(
            reason="not_invocable",
            message=(f"'{resolved}' was probed at destination {account_id}/{region} and refused (error: {evidence.error_code or 'unknown'})."),
        )

    # All gates passed — the only success path requires fresh proven evidence.
    return SelectionResult(
        canonical_model_id=resolved,
        compatibility_class=compat_class,
        harness_contract_revision=catalogue_entry.harness_contract_revision,
        evidence_verified_at=evidence.verified_at_utc,
    )


# ---------------------------------------------------------------------------
# Allowlist report (§5, C2)
# ---------------------------------------------------------------------------


def report_allowlist_coverage(
    allowlist_patterns: list[str],
) -> list[dict]:
    """Report which canonical IDs each allowlist pattern matches.

    Returns a list of dicts with: pattern, matched_ids, empty (bool).
    This is the D3/C2 migration report (steps 1-2 of §5).
    """
    report = []
    for pattern in allowlist_patterns:
        matched = [m.canonical_model_id for m in PLATFORM_MODEL_CATALOGUE if fnmatch.fnmatch(m.canonical_model_id, pattern)]
        report.append(
            {
                "pattern": pattern,
                "matched_ids": matched,
                "empty": len(matched) == 0,
            }
        )
    return report
