"""ResearchProposal model — insight generation + human approval (EPIC-G, US-G3).

Stores structured research proposals generated by the analysis agent from
scanner findings. Each proposal has a status workflow:
  proposed -> approved / rejected
  approved -> in_progress -> completed / failed
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Numeric, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base

# Valid proposal statuses
VALID_STATUSES = (
    "proposed",
    "approved",
    "rejected",
    "in_progress",
    "completed",
    "failed",
)

# Valid status transitions
STATUS_TRANSITIONS: dict[str, list[str]] = {
    "proposed": ["approved", "rejected"],
    "approved": ["in_progress", "rejected"],
    "rejected": [],
    "in_progress": ["completed", "failed"],
    "completed": [],
    "failed": ["proposed"],  # Allow re-proposal after failure
}


class ResearchProposal(Base):
    """A research proposal generated from scanner findings."""

    __tablename__ = "research_proposals"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    workspace_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("workspaces.id"),
        nullable=True,
        index=True,
    )
    title: Mapped[str] = mapped_column(String(1024), nullable=False)
    objective: Mapped[str] = mapped_column(Text, nullable=False)
    hypothesis: Mapped[str] = mapped_column(Text, nullable=False)
    source_findings: Mapped[str | None] = mapped_column(
        JSONB, nullable=True
    )  # List of finding UUIDs that inspired this proposal
    estimated_cost_usd: Mapped[float | None] = mapped_column(
        Numeric(10, 2), nullable=True
    )
    estimated_duration_hours: Mapped[float | None] = mapped_column(
        Numeric(6, 2), nullable=True
    )
    required_resources: Mapped[str | None] = mapped_column(Text, nullable=True)
    experiment_plan: Mapped[str | None] = mapped_column(
        JSONB, nullable=True
    )  # Step-by-step experiment plan as list of steps
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="proposed", index=True
    )
    approved_by: Mapped[str | None] = mapped_column(
        String(256), nullable=True
    )  # user_id or username
    approved_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    rejected_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )
