apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-context-sa
  namespace: agent-context
  labels:
    app.kubernetes.io/part-of: agent-context-platform
    app.kubernetes.io/component: serviceaccount
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::605440105851:role/agent-context-platform-irsa"
automountServiceAccountToken: true
