"""Verify API Gateway provenance before accepting an asserted IAM identity.

AWS_IAM integrations overwrite both headers below. The identity comes from the
verified SigV4 principal, while the independent proof is generated by Terraform,
stored in SSM, and exposed only to API Gateway and the gateway pod. Public routes
blank both values. A direct-cluster caller can therefore copy the identity header
but cannot satisfy the proof check.

The SigV4 caller does not possess or send the proof. It remains authenticated only
with IAM; the proof authenticates the edge-to-application hop. All consumers use
this helper and fail closed when trust, configuration, or proof is absent.
"""

from __future__ import annotations

import logging
import secrets
from typing import TYPE_CHECKING

from starlette.requests import Request

from src.shared.config import get_settings

if TYPE_CHECKING:
    from src.shared.config import Settings

logger = logging.getLogger(__name__)

# The header API Gateway maps `context.identity.userArn` into on AWS_IAM routes.
CALLER_IDENTITY_HEADER = "X-Caller-Identity"
EDGE_PROVENANCE_HEADER = "X-Adp-Edge-Provenance"


def _emit_rejection(reason: str, path: str) -> None:
    """Record a rejected identity assertion.

    Issue #5653 step 7. Without this, a legitimate caller broken by the tightening
    surfaces as an unexplained 401/403 downstream instead of as a signal at the
    point of rejection. The ARN is deliberately NOT logged: it is
    attacker-controlled on exactly the requests that reach here, so logging it
    invites log injection and writes an unverified principal name into the audit
    trail this issue exists to make trustworthy.
    """
    logger.warning("Rejected X-Caller-Identity assertion: reason=%s path=%s", reason, path)
    try:
        from src.shared.metrics import emit_caller_provenance_rejected

        emit_caller_provenance_rejected(reason=reason)
    except Exception:  # pragma: no cover - metrics must never break auth
        logger.debug("Failed to emit provenance rejection metric", exc_info=True)


def has_caller_identity_assertion(request: Request) -> bool:
    """Whether the request asserts a caller identity at all.

    Lets callers tell "asserted nothing" (fall through to bearer-token auth) apart
    from "asserted something that failed provenance". Reports only that a non-empty
    value is present; says nothing about whether it can be trusted.
    """
    return bool(request.headers.get(CALLER_IDENTITY_HEADER, "").strip())


def verified_caller_identity(request: Request, settings: Settings | None = None) -> str | None:
    """Return the asserted IAM ARN only where the edge vouches for it.

    ``None`` means no trustworthy assertion — either none was made, or header trust
    is disabled so no assertion can be believed. Never raises: resolving the ARN to
    a principal (and rejecting an unregistered one) is the caller's job. This
    answers only "may I believe this ARN at all?".

    ``settings`` is an explicit seam, and it is load-bearing rather than cosmetic.
    Each of the three consumers resolves configuration through the ``get_settings``
    imported into *its own* module. If this helper always resolved settings through
    ``src.auth.caller_provenance.get_settings`` instead, it would read a *different*
    Settings object than the call site that invoked it whenever that object is
    overridden per-module — which is exactly what the existing tests do, and what
    made the first cut of this change reject the legitimate IRSA path with a 403
    (a correctly registered internal worker presenting a genuine edge-written
    assertion). Passing the caller's own settings keeps one trust decision shared
    across all three consumers while letting each resolve configuration the way it
    already does. Omitting it falls back to this module's own lookup.
    """
    asserted = request.headers.get(CALLER_IDENTITY_HEADER, "").strip()
    if not asserted:
        return None

    if settings is None:
        settings = get_settings()
    if not settings.trust_apigw_headers:
        _emit_rejection("header_trust_disabled", request.url.path)
        return None

    configured_provenance = getattr(settings, "apigw_provenance_secret", "")
    expected_provenance = configured_provenance.strip() if isinstance(configured_provenance, str) else ""
    supplied_provenance = request.headers.get(EDGE_PROVENANCE_HEADER, "").strip()
    if not expected_provenance:
        _emit_rejection("provenance_secret_unconfigured", request.url.path)
        return None
    if not supplied_provenance or not secrets.compare_digest(supplied_provenance, expected_provenance):
        _emit_rejection("invalid_edge_provenance", request.url.path)
        return None

    return asserted
