#!/usr/bin/env bash
# Wave 2 fixture step 4 — prove the three identities are REAL and reach the
# fixture through the genuine AWS_IAM edge transport.
#
# Issue #3968 / epic #3959. Deliverable (3) of the assignment.
#
# The claim this step must establish, and the shortcut it must refuse:
#
#   The harness sends `Authorization: Bearer $<role>` for owner / nonowner /
#   other_tenant and grades the gateway's answers. That only means anything if all
#   three are authentic sessions for genuinely distinct principals, reaching the
#   pod over the path that supplies trusted provenance.
#
#   The forbidden shortcut is setting `X-Caller-Identity` by hand. On the AWS_IAM
#   routes API Gateway OVERWRITES that header from `context.identity.userArn` --
#   the verified SigV4 principal -- and injects `X-Adp-Edge-Provenance`, a secret
#   generated by Terraform and known only to API Gateway and the pod. A
#   direct-to-ALB caller can copy the identity header but cannot produce the proof,
#   and `verified_caller_identity()` fails closed without it. So a forged header
#   does not merely violate a rule: it produces a 403 and therefore proves nothing.
#
# This script therefore VERIFIES rather than mints. It confirms:
#   1. each supplied token resolves to a distinct, real principal;
#   2. the three principals differ in the ways the checks depend on (different
#      user, and a genuinely different tenant for other_tenant);
#   3. requests carrying them arrive with edge-written provenance, by observing
#      that the route the harness will use is one API Gateway signs for;
#   4. no request this script makes sets X-Caller-Identity or the proof header.
#
# Minting the sessions is ROOT'S step. It is NOT true that it requires an
# interactive GitHub OAuth login: an earlier revision of this comment said so, and
# root corrected it. The gateway ships non-interactive Cognito paths --
# src/auth/cli_login.py mints on the CLI app client via AdminSetUserPassword +
# AdminInitiateAuth (ADMIN_USER_PASSWORD_AUTH), the same mechanism the
# github-auth-broker uses on every browser sign-in, and src/auth/cli_native_login.py
# covers native-password users. So disposable sessions can be supplied without a
# browser and without creating live identities.
#
# It remains root's step because minting requires pool-admin credentials this
# script must not hold: no session value is ever passed as argv, echoed or written
# to an artifact here -- only env var NAMES. See the report this writes for exactly
# what to produce. Labeled, not silently skipped.
#
# Usage:
#   ./40-verify-edge-sessions.sh --evidence-dir <dir> --gateway-url <url> \
#       --owner-token-env VAR --nonowner-token-env VAR --other-tenant-token-env VAR \
#       [--api-url <apigw-invoke-url>]
#
# Token VALUES are read from the named environment variables and never logged,
# echoed, or written to the evidence. Only the variable NAMES appear.

set -euo pipefail

EVIDENCE_DIR=""; GATEWAY_URL=""; API_URL=""
OWNER_ENV=""; NONOWNER_ENV=""; OTHER_ENV=""
FIXTURE_POD=""; RUN_ID=""
GW_NS="${W2_GW_NS:-adp-gateway}"

while [ $# -gt 0 ]; do
  case "$1" in
    --evidence-dir)           EVIDENCE_DIR="${2:?}"; shift 2 ;;
    --gateway-url)            GATEWAY_URL="${2:?}"; shift 2 ;;
    --api-url)                API_URL="${2:?}"; shift 2 ;;
    --fixture-pod)            FIXTURE_POD="${2:?}"; shift 2 ;;
    --run-id)                 RUN_ID="${2:?}"; shift 2 ;;
    --gateway-namespace)      GW_NS="${2:?}"; shift 2 ;;
    --owner-token-env)        OWNER_ENV="${2:?}"; shift 2 ;;
    --nonowner-token-env)     NONOWNER_ENV="${2:?}"; shift 2 ;;
    --other-tenant-token-env) OTHER_ENV="${2:?}"; shift 2 ;;
    *) printf 'unknown argument: %s\n' "$1" >&2; exit 2 ;;
  esac
done

fail() { printf 'FAIL: %s\n' "$*" >&2; exit 1; }
ok()   { printf 'ok   %s\n' "$*"; }
note() { printf '     %s\n' "$*"; }

[ -n "$EVIDENCE_DIR" ] || fail "--evidence-dir is required"

# A fixture measurement needs BOTH a pod and the run id it must belong to. The pod
# name alone would let any pod be exercised and filed under this run; the run id is
# what the pod's own label is checked against.
if [ -n "$FIXTURE_POD" ]; then
  [ -n "$RUN_ID" ] || fail "--fixture-pod requires --run-id: the pod's fixture label is checked
       against that run id, and without it any pod -- including the ordinary gateway --
       could be exercised and recorded as a fixture measurement."
else
  [ -n "$GATEWAY_URL" ] || fail "one of --fixture-pod (with --run-id) or --gateway-url is required.
       --fixture-pod gives a fixture-scoped result; --gateway-url reaches the ordinary
       deployment and is recorded as fixture_scoped: false."
  RUN_ID="${RUN_ID:-unscoped}"
fi
for pair in "owner:$OWNER_ENV" "nonowner:$NONOWNER_ENV" "other_tenant:$OTHER_ENV"; do
  role="${pair%%:*}"; var="${pair#*:}"
  [ -n "$var" ] || fail "--${role//_/-}-token-env is required. All three identities are needed to tell
       'not yours' apart from 'does not exist' -- with two, a 404 for a foreign row is
       indistinguishable from a missing row."
done

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../../../.." && pwd)"
ART="$EVIDENCE_DIR/artifacts"
mkdir -p "$ART"

# Resolved by NAME so no token is ever a process argument (arguments are visible
# in `ps` to every process on the host).
for pair in "owner:$OWNER_ENV" "nonowner:$NONOWNER_ENV" "other_tenant:$OTHER_ENV"; do
  role="${pair%%:*}"; var="${pair#*:}"
  value="$(printenv "$var" || true)"
  [ -n "$value" ] || fail "\$$var (the $role identity) is unset or empty. Root supplies these at
       execution time; this script must not contain or mint them."
done
ok "all three identity env vars are present (values not read into the log)"

printf '\n== verifying the edge transport configuration (read-only, from source) ==\n'

# Which routes API Gateway signs, and which it blanks. Read from the Terraform
# that generates the OpenAPI body rather than asserted, so this cannot drift from
# what is deployed without the mismatch showing up here.
python3 - "$REPO_ROOT" "$ART/edge_transport.json" "$GATEWAY_URL" "$API_URL" \
  "$OWNER_ENV" "$NONOWNER_ENV" "$OTHER_ENV" "$FIXTURE_POD" <<'PY'
import json, re, sys
from pathlib import Path

repo, out, gateway_url, api_url, owner_env, nonowner_env, other_env, fixture_pod = sys.argv[1:9]
tf = Path(repo) / "modules/gateway/infra/modules/api-gateway/main.tf"
if not tf.is_file():
    print(f"FAIL: cannot find {tf}", file=sys.stderr)
    raise SystemExit(1)
src = tf.read_text()

# The two mapping blocks. `verified_caller_identity` maps the header from the
# SigV4 principal; `blank_caller_identity` replaces whatever the client sent.
verified = re.search(r"verified_caller_identity\s*=\s*\{(.*?)\n\s*\}", src, re.S)
blank = re.search(r"blank_caller_identity\s*=\s*\{(.*?)\n\s*\}", src, re.S)
if not verified or not blank:
    print("FAIL: could not read the caller-identity mapping locals from the API Gateway module. "
          "Refusing to guess: claiming edge provenance without reading its configuration is "
          "exactly the unproven assertion this step exists to avoid.", file=sys.stderr)
    raise SystemExit(1)

vblock, bblock = verified.group(1), blank.group(1)
identity_from_sigv4 = "context.identity.userArn" in vblock
proof_injected = "X-Adp-Edge-Provenance" in vblock
client_value_blanked = "X-Caller-Identity" in bblock and "''" in bblock

# Which paths carry AWS_IAM, and which are auth-NONE. Recorded so the operator can
# see whether the route the harness uses is a signed one.
#
# Sliced by path key rather than matched with one regex per block: the nested
# `security = [{ sigv4 = [] }]` line contains braces, so any "everything up to the
# next brace" pattern silently matches nothing and reports that the edge signs no
# routes at all -- a false negative that would look like a broken edge.
#
# The auth TYPE is then read from the actual declaration, not by asking whether
# "AWS_IAM" appears somewhere in the block. Two reasons, both observed here: the
# module's comments discuss AWS_IAM on routes that are auth-NONE, and the last
# block extends to end-of-file and so absorbs every later mention. Substring
# matching classified the human JWT route `/{proxy+}` as IAM-signed -- the exact
# inversion that would make a forged-header path look legitimately signed.
path_keys = [(m.start(), m.group(1)) for m in re.finditer(r'^\s{6}"(/[^"]*)"\s*=\s*\{', src, re.M)]
AUTH_DECL = re.compile(r'^\s*"x-amazon-apigateway-auth"\s*=\s*\{\s*type\s*=\s*"([A-Z_]+)"', re.M)
iam_paths, none_auth_paths = [], []
for index, (start, path) in enumerate(path_keys):
    end = path_keys[index + 1][0] if index + 1 < len(path_keys) else len(src)
    block = re.sub(r"#.*$", "", src[start:end], flags=re.M)  # comments are not configuration
    declared = AUTH_DECL.search(block)
    if declared and declared.group(1) == "AWS_IAM":
        iam_paths.append(path)
    else:
        none_auth_paths.append(path)
iam_paths, none_auth_paths = sorted(set(iam_paths)), sorted(set(none_auth_paths))
if not path_keys:
    print("FAIL: parsed zero route definitions out of the API Gateway module. An empty route list "
          "would be recorded as 'the edge signs nothing', which is a false negative rather than an "
          "observation. The module's shape has changed; fix this parser.", file=sys.stderr)
    raise SystemExit(1)

payload = {
    "identity_header_from_verified_sigv4": identity_from_sigv4,
    "edge_proof_header_injected_by_apigw": proof_injected,
    "client_supplied_identity_blanked_on_none_auth": client_value_blanked,
    "aws_iam_paths": iam_paths,
    "none_auth_paths": none_auth_paths,
    "gateway_url_under_test": gateway_url,
    "apigw_invoke_url": api_url or None,
    # Root's blocker 7 requires the two halves to be distinguished by SCOPE, not
    # just by auth mode. They are not equally strong claims, and collapsing them
    # would overstate what was verified:
    #
    #   * The human bearer path is exercised against the fixture directly, in
    #     cluster, with real sessions and no fabricated headers. Fixture-scoped.
    #   * The AWS_IAM path is exercised HERE against the ORDINARY edge only. Those
    #     routes are http_proxy/VPC_LINK to one Terraform-variable ALB ARN,
    #     terminating at Service `bedrockgateway` -> pods labelled
    #     app=bedrockgateway, so genuine edge provenance reaches the ORDINARY
    #     deployment. What is recorded here is an OBSERVATION of the deployed edge
    #     configuration, not a fixture measurement.
    #
    # Marked explicitly so a reader cannot mistake the second for the first. The
    # three workarounds that would make the ORDINARY edge fixture-scoped are all
    # dishonest (fabricate the headers -- forbidden, and the pod 403s; repoint the
    # ordinary Service -- an outage; run the fixture AS the ordinary deployment --
    # breaches DP-INV-1), which is why the real answer was a separate edge: #5836
    # built one, and its internal plane DOES reach fixture pods. This script does not
    # drive it, so the flag below reports which edge was measured rather than what is
    # measurable. Full evidence:
    # platform/scripts/operator/wave2/FIXTURE-ROUTING-CONSTRAINT.md
    #
    # `fixture_scoped` for the human path is NOT a literal here. It reflects whether
    # THIS invocation was given a fixture pod to exercise. Writing True
    # unconditionally -- which an earlier revision did -- claimed a fixture
    # measurement on runs that sent every request to the ordinary gateway, because
    # an operator host cannot route to a fixture ClusterIP. The authoritative,
    # per-session value is derived in lib/edge_sessions.py from the pod's own
    # verified label and lands in identity_sessions.json.
    "verification_scope": {
        "human_bearer_auth_none": {
            "fixture_scoped": bool(fixture_pod),
            "method": (
                "real sessions executed inside the verified fixture pod; no fabricated headers"
                if fixture_pod else
                "real sessions, but sent to a routable URL that terminates at the ORDINARY "
                "deployment -- not a fixture measurement; pass --fixture-pod for one"
            ),
            "authoritative_value_in": "identity_sessions.json .fixture_scoped",
        },
        "sigv4_internal_aws_iam": {
            "fixture_scoped": False,
            "method": "observation of the deployed ORDINARY edge configuration only",
            "why_not": ("this script drives the ORDINARY edge, whose AWS_IAM routes proxy to "
                        "one ALB ARN with Service selector app=bedrockgateway -- so "
                        "genuine-provenance traffic here reaches ordinary pods. Not a "
                        "statement that the path is unmeasurable: #5836's separate fixture "
                        "edge routes its internal plane to the fixture's own Service, and "
                        "10-create-fixture.sh --worker-job requires that endpoint"),
            "evidence": "platform/scripts/operator/wave2/FIXTURE-ROUTING-CONSTRAINT.md",
        },
    },
    # Named, never valued.
    "identity_env_vars": {"owner": owner_env, "nonowner": nonowner_env, "other_tenant": other_env},
    "headers_this_script_sets": ["Authorization"],
    "forged_provenance_headers_sent": False,
    "_provenance": {
        "source": "modules/gateway/infra/modules/api-gateway/main.tf",
        "note": ("read from the Terraform that generates the deployed OpenAPI body; the pod-side "
                 "check is modules/gateway/src/auth/caller_provenance.py:verified_caller_identity"),
        # Stated explicitly so this artifact is not read as a stronger claim than it
        # makes. The edge has two paths, and the three harness identities use the
        # first one:
        #   * human bearer sessions (owner/nonowner/other_tenant) traverse the
        #     auth-NONE routes, where API Gateway BLANKS X-Caller-Identity and the
        #     proof header, and FastAPI validates the JWT. Their authenticity is
        #     established by the gateway resolving each token to a distinct
        #     principal -- which is what identity_sessions.json records.
        #   * SigV4 agent/internal callers traverse the AWS_IAM routes, where the
        #     identity header is written from the verified principal and the edge
        #     proof is injected. That is the provenance path a worker-originated
        #     control command depends on.
        # Neither path lets a client assert its own identity: one blanks the header,
        # the other overwrites it. That is the property being recorded here.
        "transport_split": {
            "human_bearer_identities": "auth-NONE routes; identity/proof headers blanked by the edge",
            "sigv4_agent_identities": "AWS_IAM routes; identity from context.identity.userArn + edge proof",
            "harness_identity_roles_use": "human_bearer_identities",
        },
    },
}
Path(out).write_text(json.dumps(payload, indent=2) + "\n")
print(f"ok   wrote {out}")
for key in ("identity_header_from_verified_sigv4", "edge_proof_header_injected_by_apigw",
            "client_supplied_identity_blanked_on_none_auth"):
    print(f"     {key}: {payload[key]}")
print(f"     AWS_IAM paths: {iam_paths}")
print(f"     scope: human bearer = fixture_scoped {bool(fixture_pod)}; "
      "SigV4/AWS_IAM = fixture_scoped False (edge observation only)")
if not (identity_from_sigv4 and proof_injected and client_value_blanked):
    print("     NOTE: recorded as observed. A false here means the edge does not supply the trusted\n"
          "           provenance these checks depend on -- report it, do not compensate for it.",
          file=sys.stderr)
PY

printf '\n== verifying the three sessions are real and distinct ==\n'
if [ -n "$FIXTURE_POD" ]; then
  note "transport: exec into $GW_NS/$FIXTURE_POD (fixture-scoped, if the pod verifies)"
else
  note "transport: HTTP from this host to $GATEWAY_URL"
  note "  NOT fixture-scoped: a routable URL terminates at the ordinary deployment's"
  note "  pods by Service selector. Pass --fixture-pod for a fixture measurement."
fi
# `set -e` suspended: a non-zero exit here is the EXPECTED outcome when root has
# not yet minted the three sessions, and the instructions for producing them are
# printed in the failure branch below. Under `set -e` the script would die on that
# exit and the operator would see a bare non-zero status with no next step.
#
# The session logic lives in lib/edge_sessions.py rather than in a heredoc here,
# so it is unit-tested without a cluster (tests/test_edge_sessions.py) -- including
# the property that matters most: `fixture_scoped` is DERIVED from the verified
# transport and an external URL can never earn it.
set +e
python3 "$HERE/lib/edge_sessions_cli.py" \
  --out "$ART/identity_sessions.json" \
  --run-id "$RUN_ID" \
  --gateway-url "$GATEWAY_URL" \
  --fixture-namespace "$GW_NS" \
  ${FIXTURE_POD:+--fixture-pod "$FIXTURE_POD"} \
  --owner-token-env "$OWNER_ENV" \
  --nonowner-token-env "$NONOWNER_ENV" \
  --other-tenant-token-env "$OTHER_ENV"
rc=$?
set -e

printf '\n'
if [ "$rc" -eq 0 ]; then
  ok "three distinct authenticated identities confirmed through the real transport"
  note "artifacts: $ART/edge_transport.json, $ART/identity_sessions.json"
else
  note "session verification reported problems (rc=$rc); they are recorded in"
  note "$ART/identity_sessions.json rather than smoothed over."
  note ""
  note "MINTING THE SESSIONS IS ROOT'S STEP -- it needs pool-admin credentials this"
  note "script must not hold. It does NOT need an interactive browser login:"
  note "src/auth/cli_login.py mints non-interactively (AdminSetUserPassword +"
  note "ADMIN_USER_PASSWORD_AUTH), so disposable sessions need no live identity."
  note "What is needed:"
  note "  * owner        : the identity that owns the seeded row"
  note "  * nonowner     : a different user in the SAME tenant as owner"
  note "  * other_tenant : a user in a DIFFERENT tenant"
  note "Export each bearer token into the env var names passed to this script."
fi
exit "$rc"
