apiVersion: v1
kind: Namespace
metadata:
  name: adp-gateway-evals
  labels:
    app.kubernetes.io/part-of: adp
    app.kubernetes.io/component: gateway-evals
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
