# VENDORED — DO NOT EDIT THIS FILE.
#
# Source of truth:
#   modules/domain-apps/cyber/agent/skills/url-analysis/denylist.py
#
# Why vendored rather than imported (#5658):
# The ingestion image is a separate Python deployment image built from
# modules/agent-context/images/ingestion/ as its Docker build context. It
# cannot import across module boundaries at runtime, and the canonical module
# is stdlib-only, so a copy is the cheapest correct option.
#
# Why a drift test guards it:
# A previous unguarded copy of this file (.claude/skills/url-analysis/) drifted
# to 206 lines and silently lost IPv4 canonicalisation and check_connect_address
# entirely — i.e. it kept the API and lost the security. Copying without a
# byte-identity test is how that happens, so
# tests/unit/test_url_denylist_vendoring.py asserts every byte below matches the
# source of truth. Change the canonical file, then re-sync this one.
# --- END VENDOR BANNER ---
"""
URL destination validation — refuses analysis targets that point into internal
or otherwise non-routable network space.

The decision is made on the *canonical* address, never on how the address was
spelled. Every candidate is normalised first (integer / octal / hexadecimal
IPv4 forms, and IPv4 addresses embedded in IPv6 via ::ffff:, 6to4 and NAT64),
so equivalent notations cannot take different paths through the check.

Refuses:
- Anything the standard library classifies as loopback, link-local, site-local,
  multicast, unspecified, reserved, private, or not globally routable
- Extra ranges that classification does not reliably cover (carrier-grade NAT,
  6to4 relay anycast, NAT64, IPv4-mapped IPv6) plus the cloud metadata endpoints
- Custom host patterns (glob-style)
- Hostnames that cannot be resolved, and hostnames resolving to a mixture of
  permitted and refused addresses (fail closed)

This module decides; it does not enforce on its own. Enforcement at the
connection boundary lives in `browser_guard.py`, which is the only supported
way to obtain a browser session for URL analysis.
"""

from __future__ import annotations

import ipaddress
import re
import socket
from dataclasses import dataclass, field
from fnmatch import fnmatch
from urllib.parse import parse_qsl, urlencode, urlparse, urlsplit, urlunsplit

IPAddress = ipaddress.IPv4Address | ipaddress.IPv6Address
IPNetwork = ipaddress.IPv4Network | ipaddress.IPv6Network


# Reason codes let callers and logs tell a policy refusal apart from an
# environment failure (notably RESOLUTION_FAILED, which means the analysis
# environment's resolver could not answer — not that the target is internal).
REASON_OK = "ok"
REASON_MALFORMED_URL = "malformed_url"
REASON_SCHEME_NOT_ALLOWED = "scheme_not_allowed"
REASON_NO_HOSTNAME = "no_hostname"
REASON_HOST_PATTERN = "host_pattern"
REASON_BLOCKED_ADDRESS = "blocked_address"
REASON_RESOLUTION_FAILED = "resolution_failed"
REASON_ADDRESS_NOT_APPROVED = "address_not_approved"

# Ranges that address classification does not cover, or does not cover on every
# supported Python version. This is a second layer behind classification, not
# the primary mechanism — see _classify_blocked.
DEFAULT_DENIED_CIDRS: list[str] = [
    "100.64.0.0/10",  # RFC 6598 carrier-grade NAT
    "192.88.99.0/24",  # RFC 7526 6to4 relay anycast (classified as global)
    "198.18.0.0/15",  # RFC 2544 benchmarking
    "240.0.0.0/4",  # Reserved for future use
    "::ffff:0:0/96",  # IPv4-mapped IPv6
    "64:ff9b::/96",  # RFC 6052 NAT64
    "2002::/16",  # RFC 3056 6to4
]

# Named destinations that must never be reached, regardless of configuration.
ALWAYS_BLOCKED_IPS: list[str] = [
    "169.254.169.254",  # AWS/GCP/Azure instance metadata (IMDS)
    "fd00:ec2::254",  # AWS IMDSv2 over IPv6
]


@dataclass
class DenylistConfig:
    """Configuration for URL destination checks."""

    denied_cidrs: list[str] = field(default_factory=lambda: list(DEFAULT_DENIED_CIDRS))
    denied_host_patterns: list[str] = field(default_factory=list)
    always_blocked_ips: list[str] = field(
        default_factory=lambda: list(ALWAYS_BLOCKED_IPS)
    )


@dataclass
class DenylistResult:
    """Outcome of a destination check."""

    allowed: bool
    reason: str = ""
    reason_code: str = REASON_OK
    #: Canonical addresses the check approved. The connection must be opened to
    #: one of these and no other.
    resolved_ips: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Canonicalisation
# ---------------------------------------------------------------------------

# Hosts made only of digits, dots and hex prefixes cannot be DNS names, so they
# are safe to interpret as alternate IPv4 notations.
_NUMERIC_HOST = re.compile(r"\A[0-9a-fA-F.xX]+\Z")


def normalize_backslashes(url: str) -> str:
    """
    WHATWG URL parsing — what browsers (and CDP/Playwright) actually use —
    treats a backslash the same as a forward slash for http/https URLs, so
    "http://169.254.169.254\\@good.com/" navigates to 169.254.169.254, with
    "@good.com/" as path. Python's urlparse does not do this: it reads the
    same string's hostname as "good.com", the substring after the last "@".
    Normalising before parsing makes the decision match what the browser
    will actually connect to, for every caller of check_url/check_connect_address.
    """
    return url.replace("\\", "/")


def canonical_hostname(hostname: str) -> str:
    """Return one identity for equivalent DNS hostname spellings."""
    return hostname.removesuffix(".").lower()


def _parse_alternate_ipv4(host: str) -> ipaddress.IPv4Address | None:
    """
    Parse the non-dotted-quad IPv4 forms a browser accepts: a bare integer
    (2130706433), leading-zero octal (0177.0.0.1), hexadecimal (0x7f.0.0.1),
    and short forms where the final part absorbs the remaining octets (1.1).

    Implemented here rather than via socket.inet_aton so the behaviour is the
    same on every platform's libc.
    """
    if not _NUMERIC_HOST.match(host):
        return None

    parts = host.split(".")
    if parts[-1] == "":
        parts.pop()
    if not 1 <= len(parts) <= 4:
        return None

    values: list[int] = []
    for part in parts:
        if not part:
            return None
        try:
            if part[:2].lower() == "0x":
                value = int(part, 16)
            elif part[0] == "0" and len(part) > 1:
                value = int(part, 8)
            else:
                value = int(part, 10)
        except ValueError:
            return None
        if value < 0:
            return None
        values.append(value)

    # Every part except the last must fit in one octet; the last absorbs the
    # remaining octets (inet_aton semantics).
    if any(v > 0xFF for v in values[:-1]):
        return None
    trailing_octets = 4 - len(values)
    if values[-1] >= 1 << (8 * (trailing_octets + 1)):
        return None

    packed = 0
    for value in values[:-1]:
        packed = (packed << 8) | value
    packed = (packed << (8 * (trailing_octets + 1))) | values[-1]

    try:
        return ipaddress.IPv4Address(packed)
    except ValueError:
        return None


def _unwrap_embedded_ipv4(addr: IPAddress) -> IPAddress:
    """
    Reduce an IPv6 address that merely carries an IPv4 address to that plain
    IPv4 address, so ::ffff:127.0.0.1, 2002:7f00:1::1 and 64:ff9b::7f00:1 are
    all judged as 127.0.0.1.
    """
    if not isinstance(addr, ipaddress.IPv6Address):
        return addr

    if addr.ipv4_mapped is not None:
        return addr.ipv4_mapped
    if addr.sixtofour is not None:
        return addr.sixtofour
    # NAT64 (RFC 6052 well-known prefix): the IPv4 address is the low 32 bits.
    if addr in ipaddress.IPv6Network("64:ff9b::/96"):
        return ipaddress.IPv4Address(int(addr) & 0xFFFFFFFF)
    return addr


def canonical_address(value: str) -> IPAddress | None:
    """
    Return the canonical address a string denotes, or None if it is not an
    address literal in any accepted notation.
    """
    candidate = value.strip()
    if candidate.startswith("[") and candidate.endswith("]"):
        candidate = candidate[1:-1]
    # A zone index (fe80::1%eth0) is not part of the address itself.
    candidate = candidate.split("%", 1)[0]
    if not candidate:
        return None

    try:
        addr: IPAddress = ipaddress.ip_address(candidate)
    except ValueError:
        alternate = _parse_alternate_ipv4(candidate)
        if alternate is None:
            return None
        addr = alternate

    return _unwrap_embedded_ipv4(addr)


# ---------------------------------------------------------------------------
# Decision
# ---------------------------------------------------------------------------

# Ordered most-specific first so the refusal message names the useful class
# (127.0.0.1 is both loopback and private; "loopback" is the better answer).
_CLASSIFICATIONS: tuple[tuple[str, str], ...] = (
    ("is_loopback", "a loopback address"),
    ("is_link_local", "a link-local address"),
    ("is_site_local", "a site-local address"),
    ("is_multicast", "a multicast address"),
    ("is_unspecified", "an unspecified address"),
    ("is_reserved", "a reserved address"),
    ("is_private", "a private address"),
)


def _classify_blocked(addr: IPAddress) -> str | None:
    """Return why an address is internal by classification, or None."""
    for attribute, description in _CLASSIFICATIONS:
        if getattr(addr, attribute, False):
            return description
    if not addr.is_global:
        return "not globally routable"
    return None


def _parse_networks(cidrs: list[str]) -> list[IPNetwork]:
    """Parse CIDR strings into networks, skipping invalid entries."""
    networks: list[IPNetwork] = []
    for cidr in cidrs:
        try:
            networks.append(ipaddress.ip_network(cidr, strict=False))
        except ValueError:
            continue
    return networks


def check_address(addr: IPAddress, config: DenylistConfig) -> str | None:
    """
    Return the refusal reason for a canonical address, or None if permitted.

    Classification is the primary mechanism, so address space nobody
    enumerated is refused by default. The configured CIDRs and the named
    metadata endpoints are a second layer behind it.
    """
    for blocked in config.always_blocked_ips:
        blocked_addr = canonical_address(blocked)
        if blocked_addr is not None and blocked_addr == addr:
            return f"address {addr} is a cloud instance-metadata endpoint"

    classification = _classify_blocked(addr)
    if classification:
        return f"address {addr} is {classification}"

    for network in _parse_networks(config.denied_cidrs):
        if addr.version == network.version and addr in network:
            return f"address {addr} is within denied range {network}"

    return None


def _resolve_hostname(hostname: str) -> list[IPAddress]:
    """
    Resolve a hostname to canonical addresses. Returns an empty list when the
    resolver cannot answer — callers must treat that as a refusal.
    """
    try:
        results = socket.getaddrinfo(
            hostname, None, socket.AF_UNSPEC, socket.SOCK_STREAM
        )
    except (socket.gaierror, OSError, UnicodeError):
        return []

    addresses: list[IPAddress] = []
    for result in results:
        addr = canonical_address(str(result[4][0]))
        if addr is not None and addr not in addresses:
            addresses.append(addr)
    return addresses


def _matches_host_pattern(hostname: str, patterns: list[str]) -> str | None:
    """Return the matched denied glob pattern's reason, or None."""
    for pattern in patterns:
        if fnmatch(hostname, canonical_hostname(pattern)):
            return f"hostname '{hostname}' matches denied pattern '{pattern}'"
    return None


def check_url(url: str, config: DenylistConfig | None = None) -> DenylistResult:
    """
    Decide whether a URL may be fetched, and which addresses are approved.

    Fails closed: a hostname that cannot be resolved is refused with
    REASON_RESOLUTION_FAILED, and a hostname resolving to any refused address
    is refused even if it also resolves to permitted ones.

    Args:
        url: The URL to validate
        config: Destination-check configuration (defaults if None)

    Returns:
        DenylistResult. On allowed=True, `resolved_ips` holds the only
        addresses the connection may be opened to.
    """
    if config is None:
        config = DenylistConfig()

    try:
        parsed = urlparse(normalize_backslashes(url))
    except ValueError:
        return DenylistResult(
            allowed=False,
            reason="URL is malformed and cannot be parsed",
            reason_code=REASON_MALFORMED_URL,
        )

    if parsed.scheme not in ("http", "https"):
        return DenylistResult(
            allowed=False,
            reason=f"URL scheme '{parsed.scheme}' is not allowed (only http/https)",
            reason_code=REASON_SCHEME_NOT_ALLOWED,
        )

    try:
        hostname = parsed.hostname
    except ValueError:
        return DenylistResult(
            allowed=False,
            reason="URL host is malformed and cannot be parsed",
            reason_code=REASON_MALFORMED_URL,
        )
    if not hostname:
        return DenylistResult(
            allowed=False,
            reason="URL has no hostname",
            reason_code=REASON_NO_HOSTNAME,
        )
    hostname = canonical_hostname(hostname)

    pattern_match = _matches_host_pattern(hostname, config.denied_host_patterns)
    if pattern_match:
        return DenylistResult(
            allowed=False, reason=pattern_match, reason_code=REASON_HOST_PATTERN
        )

    literal = canonical_address(hostname)
    if literal is not None:
        reason = check_address(literal, config)
        if reason:
            return DenylistResult(
                allowed=False,
                reason=reason,
                reason_code=REASON_BLOCKED_ADDRESS,
                resolved_ips=[str(literal)],
            )
        return DenylistResult(allowed=True, resolved_ips=[str(literal)])

    addresses = _resolve_hostname(hostname)
    if not addresses:
        return DenylistResult(
            allowed=False,
            reason=(
                f"hostname '{hostname}' could not be resolved from the analysis "
                "environment, so its destination cannot be vetted"
            ),
            reason_code=REASON_RESOLUTION_FAILED,
        )

    resolved_ips = [str(addr) for addr in addresses]
    for addr in addresses:
        reason = check_address(addr, config)
        if reason:
            return DenylistResult(
                allowed=False,
                reason=f"hostname '{hostname}' resolves to a denied address: {reason}",
                reason_code=REASON_BLOCKED_ADDRESS,
                resolved_ips=resolved_ips,
            )

    return DenylistResult(allowed=True, resolved_ips=resolved_ips)


def check_connect_address(
    ip: str,
    approved_ips: list[str],
    config: DenylistConfig | None = None,
) -> DenylistResult:
    """
    Re-validate the address a connection is actually being opened to.

    Guards the gap between deciding and connecting: an address that is not in
    the approved set is refused even if it would pass the classification
    checks on its own, so a decision made about one address cannot be honoured
    against another.
    """
    if config is None:
        config = DenylistConfig()

    addr = canonical_address(ip)
    if addr is None:
        return DenylistResult(
            allowed=False,
            reason=f"connect address '{ip}' is not a valid address",
            reason_code=REASON_MALFORMED_URL,
        )

    reason = check_address(addr, config)
    if reason:
        return DenylistResult(
            allowed=False,
            reason=reason,
            reason_code=REASON_BLOCKED_ADDRESS,
            resolved_ips=[str(addr)],
        )

    approved = {canonical_address(candidate) for candidate in approved_ips}
    if addr not in approved:
        return DenylistResult(
            allowed=False,
            reason=(
                f"connect address {addr} was not in the vetted set "
                f"{sorted(str(a) for a in approved if a is not None)}"
            ),
            reason_code=REASON_ADDRESS_NOT_APPROVED,
            resolved_ips=[str(addr)],
        )

    return DenylistResult(allowed=True, resolved_ips=[str(addr)])


def scrub_url_credentials(url: str) -> str:
    """
    Remove credentials from a URL before logging or persistence.

    Userinfo, sensitive query values and fragments are never retained. If the
    URL cannot be parsed safely, return a fixed placeholder rather than risk
    returning the original secret-bearing input.
    """
    try:
        parsed = urlsplit(url)
        hostname = parsed.hostname
        if hostname is None and parsed.netloc:
            return "<redacted-unparseable-url>"

        netloc = parsed.netloc
        if parsed.username is not None or parsed.password is not None:
            host = hostname or ""
            if ":" in host and not host.startswith("["):
                host = f"[{host}]"
            try:
                port = parsed.port
            except ValueError:
                return "<redacted-unparseable-url>"
            netloc = f"[REDACTED]@{host}"
            if port is not None:
                netloc = f"{netloc}:{port}"

        sensitive_name = re.compile(
            r"(?:api[-_]?key|token|secret|pass(?:word|wd)?|auth|credential|"
            r"session|signature|sig|code|key|sid)",
            re.IGNORECASE,
        )
        query = urlencode(
            [
                (name, "REDACTED" if sensitive_name.search(name) else value)
                for name, value in parse_qsl(
                    parsed.query.replace(";", "&"), keep_blank_values=True
                )
            ],
            doseq=True,
        )
        fragment = "REDACTED" if parsed.fragment else ""
        scrubbed = urlunsplit((parsed.scheme, netloc, parsed.path, query, fragment))
    except (TypeError, UnicodeError, ValueError):
        return "<redacted-unparseable-url>"

    return scrubbed.replace("\r", "").replace("\n", "")[:2048]
