apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bedrockgateway
  namespace: adp-gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bedrockgateway
  minReplicas: 2
  maxReplicas: 12
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: "1000m"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      selectPolicy: Max
      policies:
        - type: Pods
          value: 4
          periodSeconds: 60
        - type: Percent
          value: 100
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 120
      selectPolicy: Min
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
