# =============================================================================
# GitLab OmniAuth OIDC Configuration — Cognito Integration
# =============================================================================
# Auto-generated by Terraform. Do not edit manually.
# =============================================================================

gitlab_rails['omniauth_enabled'] = true
gitlab_rails['omniauth_allow_single_sign_on'] = ['openid_connect']
gitlab_rails['omniauth_auto_sign_in_with_provider'] = :openid_connect
gitlab_rails['omniauth_block_auto_created_users'] = false
gitlab_rails['omniauth_providers'] = [
  {
    name: "openid_connect",
    label: "ADP (Cognito)",
    args: {
      name: "openid_connect",
      scope: ["openid", "email", "profile"],
      response_type: "code",
      issuer: "${oidc_issuer}",
      discovery: true,
      client_auth_method: "basic",
      uid_field: "sub",
      client_options: {
        identifier: "${oidc_client_id}",
        secret: "${oidc_client_secret}",
        redirect_uri: "https://${gitlab_domain}/users/auth/openid_connect/callback"
      }
    }
  }
]
