name: Cyber Infra Apply
'on':
  workflow_dispatch: null
concurrency:
  group: tf-apply-cyber
  cancel-in-progress: false
jobs:
  apply:
    name: Terraform Apply
    runs-on: arc-runner-org
    permissions:
      contents: read
      pull-requests: read
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - name: Run cyber app automation
      uses: ./modules/domain-apps/cyber/ci/cyber-infra-apply
