name: Cyber Worker Build
'on':
  push:
    paths:
    - modules/domain-apps/cyber/workers/**
    - modules/domain-apps/cyber/codebuild/bs-cyber-worker.yml
    - platform/scripts/zip-source.sh
    - .github/workflows/cyber-worker-build.yml
    - modules/domain-apps/cyber/ci/cyber-worker-build/**
    branches:
    - main
  workflow_dispatch: {}
jobs:
  build:
    name: Build Cyber Worker Image
    runs-on: arc-runner-org
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v7
    - name: Run cyber app automation
      uses: ./modules/domain-apps/cyber/ci/cyber-worker-build
