"""initial schema

Revision ID: 2d414a0df89d
Revises:
Create Date: 2026-02-14 07:52:23.296125
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "2d414a0df89d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bedrock_pool_accounts",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("account_id", sa.String(length=12), nullable=False),
        sa.Column("role_arn", sa.String(length=512), nullable=False),
        sa.Column("region", sa.String(length=20), nullable=False),
        sa.Column("is_healthy", sa.Boolean(), nullable=False),
        sa.Column("last_health_check", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role_arn"),
    )
    op.create_table(
        "budget_configs",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("entity_type", sa.String(length=20), nullable=False),
        sa.Column("entity_id", sa.String(length=255), nullable=False),
        sa.Column("period_type", sa.String(length=10), nullable=False),
        sa.Column("budget_amount_usd", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("enforcement_mode", sa.String(length=10), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("org_id", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "entity_type", "entity_id", "period_type", name="uq_budget_config"),
    )
    op.create_index(op.f("ix_budget_configs_org_id"), "budget_configs", ["org_id"], unique=False)
    op.create_table(
        "budget_usage",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("entity_type", sa.String(length=20), nullable=False),
        sa.Column("entity_id", sa.String(length=255), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_type", sa.String(length=10), nullable=False),
        sa.Column("total_cost_usd", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "entity_type", "entity_id", "period_start", "period_type", name="uq_budget_usage"),
    )
    op.create_index(op.f("ix_budget_usage_org_id"), "budget_usage", ["org_id"], unique=False)
    op.create_table(
        "departments",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("identity_center_group_id", sa.String(length=255), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_id", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_departments_org_id"), "departments", ["org_id"], unique=False)
    op.create_table(
        "model_aliases",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("alias_name", sa.String(length=255), nullable=False),
        sa.Column("bedrock_model_id", sa.String(length=255), nullable=False),
        sa.Column("org_id", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_model_aliases_org_id"), "model_aliases", ["org_id"], unique=False)
    op.create_table(
        "model_pricing",
        sa.Column("model_id", sa.String(length=255), nullable=False),
        sa.Column("input_price_per_1k", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("output_price_per_1k", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("model_id"),
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("aws_accounts", sa.JSON(), nullable=False),
        sa.Column("role_mappings", sa.JSON(), nullable=False),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "rate_limit_configs",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("entity_type", sa.String(length=20), nullable=False),
        sa.Column("entity_id", sa.String(length=255), nullable=False),
        sa.Column("rpm", sa.Integer(), nullable=True),
        sa.Column("tpm", sa.Integer(), nullable=True),
        sa.Column("concurrent_requests", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("org_id", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rate_limit_configs_org_id"), "rate_limit_configs", ["org_id"], unique=False)
    op.create_table(
        "service_accounts",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("department_id", sa.String(length=255), nullable=False),
        sa.Column("team_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("iam_role_arn", sa.String(length=512), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("org_id", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("iam_role_arn"),
    )
    op.create_index(op.f("ix_service_accounts_org_id"), "service_accounts", ["org_id"], unique=False)
    op.create_table(
        "teams",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("department_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("identity_center_group_id", sa.String(length=255), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_id", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_teams_department_id"), "teams", ["department_id"], unique=False)
    op.create_index(op.f("ix_teams_org_id"), "teams", ["org_id"], unique=False)
    op.create_table(
        "tokens",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=20), nullable=False),
        sa.Column("entity_id", sa.String(length=255), nullable=False),
        sa.Column("team_id", sa.String(length=255), nullable=False),
        sa.Column("department_id", sa.String(length=255), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_id", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tokens_org_id"), "tokens", ["org_id"], unique=False)
    op.create_index(op.f("ix_tokens_token_hash"), "tokens", ["token_hash"], unique=True)
    op.create_table(
        "usage_logs",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("department_id", sa.String(length=255), nullable=False),
        sa.Column("team_id", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("account_type", sa.String(length=20), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.String(length=255), nullable=True),
        sa.Column("bedrock_account_id", sa.String(length=12), nullable=True),
        sa.Column("org_id", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usage_logs_org_id"), "usage_logs", ["org_id"], unique=False)
    op.create_index(op.f("ix_usage_logs_timestamp"), "usage_logs", ["timestamp"], unique=False)
    op.create_index(op.f("ix_usage_logs_user_id"), "usage_logs", ["user_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("team_id", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("identity_center_user_id", sa.String(length=255), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_id", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_org_id"), "users", ["org_id"], unique=False)
    op.create_index(op.f("ix_users_team_id"), "users", ["team_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_team_id"), table_name="users")
    op.drop_index(op.f("ix_users_org_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_usage_logs_user_id"), table_name="usage_logs")
    op.drop_index(op.f("ix_usage_logs_timestamp"), table_name="usage_logs")
    op.drop_index(op.f("ix_usage_logs_org_id"), table_name="usage_logs")
    op.drop_table("usage_logs")
    op.drop_index(op.f("ix_tokens_token_hash"), table_name="tokens")
    op.drop_index(op.f("ix_tokens_org_id"), table_name="tokens")
    op.drop_table("tokens")
    op.drop_index(op.f("ix_teams_org_id"), table_name="teams")
    op.drop_index(op.f("ix_teams_department_id"), table_name="teams")
    op.drop_table("teams")
    op.drop_index(op.f("ix_service_accounts_org_id"), table_name="service_accounts")
    op.drop_table("service_accounts")
    op.drop_index(op.f("ix_rate_limit_configs_org_id"), table_name="rate_limit_configs")
    op.drop_table("rate_limit_configs")
    op.drop_table("organizations")
    op.drop_table("model_pricing")
    op.drop_index(op.f("ix_model_aliases_org_id"), table_name="model_aliases")
    op.drop_table("model_aliases")
    op.drop_index(op.f("ix_departments_org_id"), table_name="departments")
    op.drop_table("departments")
    op.drop_index(op.f("ix_budget_usage_org_id"), table_name="budget_usage")
    op.drop_table("budget_usage")
    op.drop_index(op.f("ix_budget_configs_org_id"), table_name="budget_configs")
    op.drop_table("budget_configs")
    op.drop_table("bedrock_pool_accounts")
    # ### end Alembic commands ###
